version: '2'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=acqua_play
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
